### ISSUE TITLE
sequencing_summary.txt file?

### ISSUE THREAD

**Issue by flashton2003** [duceppemo/fast5_demultiplexer#1]
Hello,

Today I had to demultiplex the fast5s based on the fastqs, but unfortunately i only came across your script after I'd already rolled my own.

I was wondering if you had thought about also generating the sequencing_summary.txt file? As it is needed for some applications (like nanopolish), but I haven't reverse engineered it yet. I was wondering if you have?

Ta,

Phil

**Comment by duceppemo** [comment]
I haven't because I didn't need to. If you still have to fast5 files, you can just re-basecall them ant the `sequencing_summary.txt` file will be generated again. It would be indeed be faster to generate them from the fastq, but I'm not sure all the info in se summary file is contained into the reads headers inside the fastq files. Best solution to your problem is to re-do the basecalling I believe. Nanopolish don't need the summary file either, it just makes the indexing faster.

**Comment by flashton2003** [comment]
Hi Marc-Olivier,

That's a great point thank you. Sometimes the nanopore toolchain is a bit baffling! Just re-basecall the already basecalled data... of course!

Thanks for your help.

Phil
